name: animals
description: Animals Projects for Child 

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_admob: ^0.9.3+1
  rflutter_alert: ^1.0.3
  flutter_tts: ^0.9.1
  path_provider: ^1.6.5
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets: 
    #Images
    - asset/image/lion.png
    - asset/image/goldfish.png
    - asset/image/giraffe.png
    - asset/image/zebra.png
    - asset/image/harbor_seal.png
    - asset/image/gull.png
    - asset/image/goose.png
    - asset/image/hummingbird.png
    - asset/image/fish.png
    - asset/image/skunk.png
    - asset/image/starfish.png
    - asset/image/squirrel.png
    - asset/image/squid.png
    - asset/image/sparrow.png
    - asset/image/tiger.png
    - asset/image/stork.png
    - asset/image/whale.png
    - asset/image/turtle.png
    - asset/image/turkey.png
    - asset/image/woodpecker.png
    - asset/image/wolf.png
    - asset/image/walrus.png
    - asset/image/pig.png
    - asset/image/cock.png
    - asset/image/cobra.png
    - asset/image/snake.png
    - asset/image/snails.png
    - asset/image/sloth.png
    - asset/image/hedgehog.png
    - asset/image/hippo.png
    - asset/image/horse.png
    - asset/image/hyena.png
    - asset/image/koala.png
    - asset/image/jackal.png
    - asset/image/jaguar.png
    - asset/image/jellyfish.png
    - asset/image/kangaroo.png
    - asset/image/killer_whale.png
    - asset/image/leopard.png
    - asset/image/lizard.png
    - asset/image/lobster.png
    - asset/image/lynx.png
    - asset/image/monkey.png
    - asset/image/ostrich.png 
    #New 
    - asset/image/moose.png 
    - asset/image/octopus.png 
    - asset/image/orangutan.png 
    - asset/image/owl.png 
    - asset/image/panda.png 
    - asset/image/parrot.png 
    - asset/image/peacock.png 
    - asset/image/pelican.png 
    - asset/image/pigeon.png 
    - asset/image/pinguin.png 
    - asset/image/polar_bear.png 
    - asset/image/raccoon.png 
    - asset/image/rat_mouse.png 
    - asset/image/raven.png 
    - asset/image/rhino.png  
    - asset/image/shark.png 
    - asset/image/sheep.png 
    - asset/image/shrimps.png 
    #new 2
    - asset/image/dolphin.png 
    - asset/image/donkey.png 
    - asset/image/duck.png 
    - asset/image/elephants.png 
    - asset/image/falcon.png 
    - asset/image/feather.png 
    - asset/image/ferret.png 
    - asset/image/flamingo.png 
    - asset/image/frog.png 
    #New 3
    - asset/image/Anaconda.png 
    - asset/image/Arctic.png 
    - asset/image/Bat.png 
    - asset/image/Bear.png 
    - asset/image/Beaver.png  
    - asset/image/Bison.png 
    - asset/image/boar.png 
    - asset/image/camel.png 
    - asset/image/cat.png 
    - asset/image/Cheetah.png 
    - asset/image/crab.png 
    - asset/image/crocodile.png  
    - asset/image/deer.png 
    - asset/image/dog.png 
    - asset/image/eagle.png   
    # Gif Image
    - asset/image/sadCat.gif


    #json File
    - asset/json/image.json
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: ballo
       fonts:
        - asset: asset/font/ballo.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
